name: Run Tests

on:
  push:
    branches: [main]
  pull_request_target:

jobs:
  test:
    name: PHP ${{ matrix.php }}, Laravel ${{ matrix.laravel }}
    runs-on: ubuntu-latest
#    if: contains(github.event.pull_request.labels.*.name, 'safe to test')

    strategy:
      max-parallel: 1
      matrix:
        php: [8.0, 8.1]
        laravel: [8.*, 9.*]
        include:
          - php: 8.0
            laravel: 8.*
            testbench: 6.*
            phpunit: 9.*
          - php: 8.1
            laravel: 8.*
            testbench: 6.*
            phpunit: 9.*
          - php: 8.0
            laravel: 9.*
            testbench: 7.*
            phpunit: 9.*
          - php: 8.1
            laravel: 9.*
            testbench: 7.*
            phpunit: 9.*
    services:
      stripemock:
        image: stripe/stripe-mock:v0.141.0
        ports:
          - 12111

    steps:
      - name: Get labels
        run: echo "The selected labels are ${{ github.event.pull_request.labels.*.name }}"
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: posix, dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Install dependencies
        run: |
          composer config "http-basic.nova.laravel.com" "${{ secrets.NOVA_USERNAME }}" "${{ secrets.NOVA_LICENSE_KEY }}"
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "phpunit/phpunit:${{ matrix.phpunit }}" --no-interaction --no-update
          composer update --prefer-dist --no-interaction --no-progress --no-suggest

      - name: Copy .env.example to .env
        run: cp .env.testing.example .env.testing

      - name: Run PHP tests
        run: vendor/bin/phpunit
        env:
          STRIPE_TEST_SECRET: "${{ secrets.STRIPE_SECRET }}"
          STRIPE_API_BASE: "127.0.0.1:${{ job.services.stripemock.ports[12111] }}"

      - name: Send Slack notification
        uses: 8398a7/action-slack@v3
        if: failure()
        with:
          status: ${{ job.status }}
          author_name: PHP ${{ matrix.php }}, Laravel ${{ matrix.laravel }}
          fields: repo,message,commit,author,eventName,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
